name: Deploy static content to Pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: write # Changed from read to allow pushing to gh-pages

concurrency:
  group: "pages" # This group name might be re-evaluated if it's tied to the old deployment method
  cancel-in-progress: true

jobs:
  deploy:
    # The environment block for github-pages is removed as we are switching deployment methods
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
